/**
 * MeetNow Internal Communication API
 * This is the API for internal communication between the MeetNow app on mobile devices and the backend
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface MeetingParticipants {
    /**
     * unique identifier, TODO (mail or phone?)
     */
    id?: string;

    busyTimes?: Array<models.MeetingBusyTimes>;

}
